 name 			= "Weapon Slinging"; // Name of your mod
 author 		= "Crow Studios"; // Affects Arma 3 Launcher, when the mod are loaded as local
 logo 			= "weapon_slinging_common\crow_studios_co.paa"; // Logo displayed in the main menu
 logoOver 	    = "weapon_slinging_common\crow_studios_co.paa"; // When the mouse is over, in the main menu
 tooltip 		= "";
 tooltipOwned   = "Crow Studios"; // Tool tip displayed when the mouse is left over, in the main menu
 picture 		= "weapon_slinging_common\crow_studios_co.paa"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
 actionName     = "Discord Link";
 action 		= "https://discord.gg/yMkZFS3S6c"; // Website URL, that can be accessed from the expansions menu
 overview 		= ""; // Supports structured text
 hideName 		= 0; // Hide the extension name
 hidePicture	= 0;	// Hide the extension menu
 dlcColor[] 	= {0.23,0.39,0.30,1}; // Color used for DLC stripes and backgrounds (RGBA)
 logoSmall 		= "weapon_slinging_common\crow_studios_co.paa"; // Display in creative lists, next to the entities added by the mod